version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[GH Actions]"
    open-pull-requests-limit: 5
    reviewers:
      - "mischback"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm]"
      prefix-development: "[npm dev]"
    open-pull-requests-limit: 10
    reviewers:
      - "mischback"
    pull-request-branch-name:
      separator: "-"

