name: CI default branch

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install Node modules
        run: npm ci
      - name: Run eslint
        run: make ci/linting

  testing:
    name: Run tests on ${{ matrix.os }} for Node ${{ matrix.node-version }}
    needs: linting
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup OS ${{ matrix.os }} - Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Node modules
        run: npm ci
      - name: Run tests with Jest
        run: make ci/coverage
      - name: Prepare coverage result
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: OS-${{ matrix.os }}_Node-${{ matrix.node-version }}
          path-to-lcov: ./src/.coverage/lcov.info
          parallel: true

  finish:
    name: Indicate completion to Coveralls.io
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Finished coverage collection
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./src/.coverage/lcov.info
          parallel-finished: true
