name: CI default branch

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run all Linters
        run: make ci/linting

  testing:
    name: Tests (${{ matrix.os }}, ${{ matrix.node-version }})
    needs: linting
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup OS ${{ matrix.os }} - Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: make ci/coverage
      - name: Prepare Coverage Result
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: OS-${{ matrix.os }}_Node-${{ matrix.node-version }}
          path-to-lcov: ./src/.coverage/lcov.info
          parallel: true

  dependabot:
    needs: testing
    uses: mischback/development-meta/.github/workflows/dependabot-auto-approve.yml@main
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  finish:
    name: Finish
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Publish Results to Coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./src/.coverage/lcov.info
          parallel-finished: true

