name: CI release

on:
  push:
    branches: [main, master]

jobs:
  build:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm ci
      - name: Perform the Release
        run: make ci/release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

