name: CI release

on:
  push:
    branches: [main, master]

jobs:
  build:
    name: Release to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Node modules
        run: npm ci
      - name: Run linters
        run: make ci/linting
      - name: Run test suite
        run: make ci/testing
      - name: Perform the release
        run: make ci/release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
